backend:
  - changed-files:
    - any-glob-to-any-file: "backend/**/*"

frontend:
  - changed-files:
    - any-glob-to-any-file: "frontend/**/*"

docs:
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.md"
      - "docs/**/*"

github-actions:
  - changed-files:
    - any-glob-to-any-file: ".github/workflows/**/*"
