# Generated by Django 5.2.8 on 2025-11-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING_FUNDING', 'Pending Funding'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('IN_ESCROW', 'In Escrow'), ('WORK_IN_PROGRESS', 'Work in Progress'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('CLOSED', 'Closed')], default='PENDING_FUNDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_REVIEW', 'Awaiting Review'), ('REVISION_REQUESTED', 'Revision Requested'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=20)),
                ('submission_details', models.TextField(blank=True)),
            ],
        ),
    ]
