# Generated by Django 5.2.8 on 2025-11-15 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Seller Profile', 'verbose_name_plural': 'Seller Profiles'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['name'], 'verbose_name': 'Service Category', 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief description of services and expertise'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='seller_profiles/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes about verification status'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Date when profile was verified', null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=20),
        ),
    ]
